/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSetoresRouteImport } from './routes/_authenticated/setores'
import { Route as AuthenticatedImasRouteImport } from './routes/_authenticated/imas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRegistrosIndexRouteImport } from './routes/_authenticated/registros/index'
import { Route as AuthenticatedRegistrosNovoRouteImport } from './routes/_authenticated/registros/novo'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetoresRoute = AuthenticatedSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImasRoute = AuthenticatedImasRouteImport.update({
  id: '/imas',
  path: '/imas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistrosIndexRoute =
  AuthenticatedRegistrosIndexRouteImport.update({
    id: '/registros/',
    path: '/registros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegistrosNovoRoute =
  AuthenticatedRegistrosNovoRouteImport.update({
    id: '/registros/novo',
    path: '/registros/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/imas': typeof AuthenticatedImasRoute
  '/setores': typeof AuthenticatedSetoresRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/registros/': typeof AuthenticatedRegistrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/imas': typeof AuthenticatedImasRoute
  '/setores': typeof AuthenticatedSetoresRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/registros': typeof AuthenticatedRegistrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/imas': typeof AuthenticatedImasRoute
  '/_authenticated/setores': typeof AuthenticatedSetoresRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/registros/novo': typeof AuthenticatedRegistrosNovoRoute
  '/_authenticated/registros/': typeof AuthenticatedRegistrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/imas'
    | '/setores'
    | '/usuarios'
    | '/registros/novo'
    | '/registros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/imas'
    | '/setores'
    | '/usuarios'
    | '/registros/novo'
    | '/registros'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/imas'
    | '/_authenticated/setores'
    | '/_authenticated/usuarios'
    | '/_authenticated/registros/novo'
    | '/_authenticated/registros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setores': {
      id: '/_authenticated/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof AuthenticatedSetoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imas': {
      id: '/_authenticated/imas'
      path: '/imas'
      fullPath: '/imas'
      preLoaderRoute: typeof AuthenticatedImasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registros/': {
      id: '/_authenticated/registros/'
      path: '/registros'
      fullPath: '/registros/'
      preLoaderRoute: typeof AuthenticatedRegistrosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registros/novo': {
      id: '/_authenticated/registros/novo'
      path: '/registros/novo'
      fullPath: '/registros/novo'
      preLoaderRoute: typeof AuthenticatedRegistrosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImasRoute: typeof AuthenticatedImasRoute
  AuthenticatedSetoresRoute: typeof AuthenticatedSetoresRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedRegistrosNovoRoute: typeof AuthenticatedRegistrosNovoRoute
  AuthenticatedRegistrosIndexRoute: typeof AuthenticatedRegistrosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImasRoute: AuthenticatedImasRoute,
  AuthenticatedSetoresRoute: AuthenticatedSetoresRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedRegistrosNovoRoute: AuthenticatedRegistrosNovoRoute,
  AuthenticatedRegistrosIndexRoute: AuthenticatedRegistrosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
